chp5
r4ds/bookclub-mshiny pull request #23
Opened 2021-03-24 16:43 UTC by shmuhammad2004

Chapter5 presentation

2021-03-25 11:33 UTC, russHyde requested changes
Thanks for this. Could you push the requested files as `./images/05-workflow/*.png` and rewrite the relevant paths in your chapter. I'll check if the chapter builds locally once the files are on github.

2021-03-25 11:33 UTC, russHyde commented on 05-workflow.Rmd
> +  ![](images/workflow.png)
Could you upload the figures, please.
But put the files in `./images/05-workflow/`
Then make sure that your image-links are rewritten to point to `./images/05-workflow/workflow.png` etc

2021-03-25 11:33 UTC, russHyde commented on 05-workflow.Rmd
> +  ![](images/workflow.png)
Again, please rewrite the image path

2021-03-25 11:33 UTC, russHyde commented on 05-workflow.Rmd
> +  ![](images/debugging_challenges.png)
Again, please change to `./images/05-workflow/debugging_challenges.png`

2021-03-25 11:33 UTC, russHyde commented on 05-workflow.Rmd
> +  ![](images/workflow.png)
Please change to `./images/05-workflow/workflow.png`

2021-03-30 16:29 UTC, shmuhammad2004 commented
@russHyde, please sorry for the long silence. I updated the chapter as requested.

2021-03-30 16:29 UTC, shmuhammad2004 commented on 05-workflow.Rmd
> +  ![](images/workflow.png)
Done

2021-03-30 17:30 UTC, russHyde reviewed
Looks good. There is a figure "development_cycle" that was added to the repo but wasn't used. Is there a missing image import in the .Rmd?

2021-03-31 09:26 UTC, russHyde commented
I'll merge it, but if you want to remove the unused figure, feel free to do that in another PR.

2021-03-31 09:26 UTC, russHyde approved these changes
LGTM (the unused figure isn't an issue)

2021-03-31 09:27 UTC, merged

2021-03-31 09:28 UTC, shmuhammad2004 commented
Ok.
On 31 Mar 2021, 10:27 +0100, Russ Hyde ***@***.***>, wrote:
> @russHyde approved this pull request.
> LGTM (the unused figure isn't an issue)
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.