modules chapter notes , links
r4ds/bookclub-mshiny pull request #64
Opened 2021-07-28 16:55 UTC by aammd

here is my belated contribution regarding the modules chapter! thanks again everyone for this inspiring group

2021-07-30 14:33 UTC, russHyde requested changes
Thanks so much for this. Could you make sure your example code go into a subdirectory of `./examples/`.

2021-07-30 14:33 UTC, russHyde commented on histogram.R
> +mod_histogram_ui <- function(id){
Could you move this file to `./examples/19-modules/histogram.R`

2021-07-30 14:33 UTC, russHyde commented on shiny_module_demo.R
> +  selectInput("var", "Variable", names(mtcars)),
likewise, to `./examples/19-modules/shiny_module_demo.R`

2021-07-30 14:33 UTC, russHyde commented on test.R
> +#' test UI Function
likewise to `./examples/19-modules/test.R`

2021-09-05 15:15 UTC, jonthegeek approved these changes
Looks good, thanks!

2021-09-05 15:16 UTC, merged